
name: Java CI with Gradle

on:
  push:
    branches:
    - branch_cfdeploy

#starting job
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
        
      - run: |
          ls '${{ github.workspace }}/build/libs'
          cp '${{ github.workspace }}/build/libs/gs-spring-boot-0.1.0.jar' .
      - name: Step 6 - Deploy to CF
        uses: jhunt/cf-push@v1
        with:
          api: https://api.cf.ap21.hana.ondemand.com
          username: ramyaravindra999@gmail.com
          password: Azuredevops@123
          org: 6fece677trial
          space: prod
          run : pwd
          manifest: manifest.yml
          #command: push -f manifest.yml


